name: uu_audio_session
description: Sets the iOS audio session category and Android audio attributes for your app, and manages your app's audio focus, mixing and ducking behaviour.
version: 0.1.24
homepage: https://github.com/shingohu/audio_session
topics:
  - audio
  - uu-audio-session

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter



flutter:
  plugin:
    platforms:
      android:
        package: com.shingo.audio_session
        pluginClass: AudioSessionPlugin
      ios:
        pluginClass: UUAudioSessionPlugin
